[package]
name = "luz_optimon"
version = "0.1.0"
edition = "2024"

[dependencies]
lunaluz_core = { path = "../../crates/lunaluz_core" }
serde.workspace = true
serde_json.workspace = true
chrono.workspace = true
iso8601-duration.workspace = true
tokio.workspace = true
axum.workspace = true
enum_dispatch.workspace = true
clap.workspace = true

[profile.release]
lto = true # link time optimization
codegen-units = 1 